In [2]:
import pandas as pd
import numpy as np
import scipy
import scipy.stats as sp
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df_cancer = pd.read_csv("datasets/BCSprep.csv")
df_cancer.head()

,id,age,pathsize,lnpos,histgrad,er,pr,status,time,lnpos_YN,pathsize_Cat
0,1.0,60.0,NaN,0.0,3.0,0.0,0.0,0.0,9.466667,No,NaN
1,2.0,79.0,NaN,0.0,NaN,NaN,NaN,0.0,8.600000,No,NaN
2,3.0,82.0,NaN,0.0,2.0,NaN,NaN,0.0,19.333333,No,NaN
3,4.0,66.0,NaN,0.0,2.0,1.0,1.0,0.0,16.333333,No,NaN
4,5.0,52.0,NaN,0.0,3.0,NaN,NaN,0.0,8.500000,No,NaN